<?php
include('Header bar.php');

?>

<!DOCTYPE html>
<html>
<head>
	<title>IDOLOGY</title>
	<link rel="stylesheet" type="text/css" href="Css/idology.css">
</head>
<body>
<div class="content">

<h2 class="heading">idology</h2>
<p>The modern world is bad. It is inhumane, unfair and unjust. This is the world of money. It is not for people. It is for those who who produce this money, for bankers and financiers, government and millionaires. And people are mere "pawns" in this game. They just serve them as attendants.</p>
<p>Why do bankers work less and earn a hundred times more?</p>
<p>What lies behind the social welfare? Labor. But why do bankers live a hundred times better than common people who really work hard? Do the bankers work harder? Definitely they don't! In addition they do not even produce any material values, as opposed to the workers. Why then the difference in income is so enormous?</p>
<p>Many wonder with all sincerity now, reading this: "Well... a banker and a worker, they cannot be compared! The banker-the head of the Bank, he has power over money, and is well-connected. And we are ordinary people, having no power or clout. Naturally, the banker lives better than we do.</p>
<p>Meanwhile, there is nothing "natural" here. The point is that everyone got used to this state of affairs and takes it as a matter of course. People believe that this is the way of the world, that a banker has to live better and it cannot be otherwise. But in reality things are different and the situation can be changed!!</p>
<p>But yet, why? Why does the banker work less, but live better? Better than a factory worker, miner, oil rigger, or woodcutter? Because the banker has always got money. Exactly! It's all about money! MONEY! This is the whole point, the cornerstone! And about it, we should talk in more details.</p>
<p>If money is a measure of labour, why is the world unjust?</p>
<p>So, what is money? Have you ever thought about it? May be it is a calculation tool or a measure of labor? As we are told from childhood, we have to work, work and work, because money won’t fall down from the sky. It should be honestly and hardly earned! Everyone was led to believe it from the cradle . It's interesting, what would billionaires say to that, who honestly and hardly earned all their billions. It's ridiculous, isn't it?</p>
<p>Well, we work without cease. But what should we expect in the end? Low wages and pensions, and no rest, but a constant struggle with debts. And half-starved old age... You have spent all your life, working for billionaires, you have been taken away all your power, energy and health, you’ve been squeezed like a lemon, and after that you’ve been just thrown into the dustbin as a write-off.</p>
<p>Is it right? But that's the world. This horrific reality of the modern society. This is what we should all expect in the end almost certainly; everything ends up in this way for the vast majority of people in today's world. As it ended up for their mothers and fathers, grandmothers and grandfathers ... As it will end up, in the present state of affairs, for their children and grandchildren ... great-grandchildren ... Then, in their turn, for their children and grandchildren ... And so on ... That's the way of the world.</p>
<p>Why? All of this is wrong, unfair! It must not exist! Why do some people have everything, but others have nothing? Why do some people walk in golden slippers, but the others barely make ends meet? They don’t know how to feed their children, although all of them “work honestly”. Why does it happen?! Yet we are all the people. We are "equal", aren’t we? Then why?!</p>
<p>Because there is a lie around us. A huge, continuous, monstrous, embellishing lie. Do not believe anything that is broadcasted daily on TV by satiated and well-groomed masters of life.</p>
<p>And people are not equal, and the money is not even a measure of labor. All of this is an insolent and shameless lie. We are surrounded by lie! And still most people trust it all and continue to live in the unfair and unjust world. Why do they cheat you? Just to make it easier to control you.</p>
<p>Is everyone of us equal? It's nonsense!</p>
<p>Imagine yourself as a billionaire now. Or even as an ordinary worthless member of the parliament. Are you equal? In what? You live in a different way, eat in a different way, and rest in a different way. In one day he spends more than you spend for a year! His wife is wearing underclothes more expensive than the whole wardrobe of your wife... He is treated in the best Swiss clinics. And what about you? His children and yours.. Have you compared? Well, where is your "equality"?</p>
<p>Perhaps, you are equal in the rights, aren&rsquo;t you? Oh, but we forgot about the rights. As it is written in the Constitution of different countries, isn&rsquo;t it? But let&#39;s try to find out, what kind of &ldquo;equal&rdquo; rights do we have with oligarchs or bankers? Just a curious!</p>
<p>The right to work? Well, we have such a right. However some really work for peanuts, whereas the others hardly do anything, earning millions and billions. Is it normal?</p>
<p>The right to elect and to be elected? Hmm ... Well, you can elect, of course, you&rsquo;re welcome. And what about &quot;to be elected&quot;? Here&#39;s quite different story. To take part in election campaigns you need a lot of money. And where is it coming from? You will never earn it as a typical worker. Therefore in government there are the people who have extensive financial stock. It&#39;s problematic to participate in the elections for an average person and there&#39;s no way to win.</p>
<p>In fact, people are not equal in anything. A constantly progressing social inequality &mdash; here&#39;s the real picture!</p>
<p>So, what is money?</p>
<p>Now we move on to money. Of course, money is not any &quot;measure of labor&quot;. These are fairy tales for idiots. Otherwise you would live like a lord. Or maybe you don&rsquo;t work much enough? Unfortunately, money is just a tool to hold all of us in slavery. We are all slaves. Slaves of money. More precisely, we are slaves of those, who print money. They are our masters.</p>
<p>In fact, nothing has been changed at all during all these centuries on Earth. We have been living so far in the slave-owning system, which has undergone merely external transformations. Everything has become just more civilized and sophisticated. If anciently slaves had real shackles &mdash; rusty and steel, then today they are merely invisible, though they still exist. We don&rsquo;t seem to have them, and can go wherever we want. There are no shackles, we are supposedly free! However, things are different. It is money that is our shackles in the modern world.</p>
<p>In practice none of us is free. &quot;Freedom&quot; is an illusion. Money &mdash; that&#39;s the point! We are really nothing without money. We need a home, clothes, food and cannot live in a cave and even to go hunting, we need money now. It is necessary to have money everywhere! Because everything around us is just for money. You cannot make a single step without it! But where can we find money? Maybe to earn it?</p>
<p>Have you ever wondered that it is immoral to trade yourself? That it is a kind of prostitution to sell your own strengths, brains, time... What is the difference from the trading your own body? Well, but you will object that people have to work. If everybody would stop doing his job, what&rsquo;s going to happen then?! We will resettle in cave again, won&rsquo;t we?</p>
<p>That&rsquo;s ridiculous. The same &quot;convincing&quot; arguments could be heard for sure in the slave society, when the slaveholders had been trying to make understand their slaves, who, for some reason, didn&rsquo;t want to work for them, and asked different questions. And later, the same arguments the landlords told their serfs clearly and confidently: &quot;After all, if you stop working, what&rsquo;s going to happen then?! Our society will collapse! And we will die of hunger!!!&quot;</p>
<p>Yes, it is necessary to work, to create something useful for the society. Otherwise the society will degrade and die. But firstly, we have to work voluntarily, not for a bowl of soup and not only in order to survive; we have to do what we like!</p>
<p>And secondly, while we are on the subject, once it is necessary to work &mdash; it is necessary for everyone. All people are equal, aren&rsquo;t they? So let everybody work. The situation, when some people earn money (in the mines, at the factory, wasting their effort and health!) while others simply print it (sitting back and sipping an exotic cocktail), is abnormal. Such a situation is not acceptable in principle. And there are no &quot;explanations&quot; and excuses to this state of affairs. Absolutely!</p>
<p>Money is just a paper, candy wrappers, which is not backed by anything tangible and, according to that, money is simply printed unrestrictedly, to anyone&#39;s heart&#39;s content. And then these candy wrappers are distributed among the slaves (among the likes of us) as &quot;wages for labor&quot;. When we are given an extra wrapper (our salary is increased) &mdash; we are happy. Are you shocked? Alas, that&#39;s our bitter reality.</p>
<p>The whole financial world is a pyramid!</p>
<p>How is the financial world organized? It is a pyramid. The Fed the U.S. Federal Reserve System is at the top of it. The Fed creates dollars. How much? As much as they want! Of course, Fed adhere to some of their own internal rules and regulations; they try, for example, not to create too many dollars to prevent complete devaluation of the currency, and etc. But in principle the Fed can create as many dollars as they want. At least, there are no any external limitations for that. Absolutely! The U.S. Fed is guided solely by the reasons of expediency.</p>
<p>The lower levels of this global pyramid are the central banks of different countries; all other local national banks are situated on even lower levels. (Of course, all of this is slightly simplified, but in general everything reflects an overall picture). Actually, why do we need banks? Speaking figuratively, banks play the role of blood vessels in the social organism. Through these vessels the money (blood) from the heart (the Central Bank) enters all its organs. Money (blood) wash these organs, it brings life to them!.. Such an interesting comparison :-))</p>
<p>In which connection dollars are mentioned here? And what relation does the Fed have to us, ordinary people? Basically, the most direct relation! After all, dollar is the global currency. No one Central Bank can print its currency in desirable quantity without permission of the U.S. Fed! It is out of question! By no means! As soon as some country supplied its resources to the USA for a billion dollars (exchanged its actual raw stock for a wagon of colored pieces of paper with the pictures of great American presidents), then it will be allowed to print the local currency in the amount of billion dollars. Now it is permitted, and this is the only way. Otherwise, such a country will be turned out from the IMF, its currency will become inconvertible and so on. In short, the measures will be taken immediately.</p>
<p>And yet, why does a banker live better than a worker? We still have no answer! He prints money, and a worker, for example, builds houses or works in mining industry. It is also very important. Does the banker work harder and give more benefits to the society? Of course not. Then why does he live better?</p>
<p>And one more interesting question in addition. I have been working and working, completing the whole plan, with a clear conscience, daily &mdash; from morning to night, for public benefit. As it seems, I have been doing my best. But anyway I can&rsquo;t pay off the loans. And all my friends are in the same situation. Is it normal? It is obviously wrong and unfair! This is eternal credit bondage. Why do we always owe money to anyone? Why are we all-time bank debtors?!</p>
<p>In short, they make fools of the common people. As usual &mdash; nothing new. The rich take advantage of the fact that we, simple hard workers, don&rsquo;t have time to figure out all these tricky schemes, we have to feed our families. That&rsquo;s why they take advantage of this situation.</p>
<p>How do banks deceive people?</p>
<p>Let&#39;s figure out quietly and without haste. But you have to strain your brains. It&#39;s not easy to unravel in a couple of minutes those things which have been tangled during the centuries by the best sophisticated minds of mankind, seeking only wealth accumulation for their personal needs.</p>
<p>Let&rsquo;s make an example. Let it be a Adam and Steven. And let it be Leonard, a banker of Adam and Steven. They both keep their money in his bank. Adam really wants to buy &hellip;.well, let&#39;s say, Steven&rsquo;s bicycle. But he has no money. More precisely, he has money, but not enough &mdash; only $10, while Steven wants as much as $100 for his precious bicycle. That is a problem!</p>
<p>What is Adam going to do? He gives Steven his $10 as a deposit and asks not to sell the bike to anyone. He says that he will bring the remaining sum soon. In the meantime he runs to his bank, to the respected Leonard, to get a loan for the missing $90.</p>
<p>As ill luck Leonard has no money at this moment, but he knows perfectly about $10, which Adam gave Steven. And where will Steven bring this money to? That&#39;s right, he will put these $10 in his lovely bank, to the same Leonard. Therefore Leonard asks Adam to come back tomorrow. In the hope that tomorrow he will get these $10.</p>
<p>And everything happens in this way. The next day Steven brings $10 to the bank, the bank provides Adam these $10 on credit. Adam immediately gives them Steven, who again puts them in a bank, the bank again provides Adam these $10 on credit, etc. As long as Adam the fool will gather enough money for the bicycle.</p>
<p>So what do we have in the end? Adam finally got the bike from Steven, but at the same time Adam owes $90 to the bank (Leonard), and the bank, in its turn, owes $100 to Steven.</p>
<p>In other words, those $10, which were existed initially, have magically turned into $200 ($190 of debts plus real $10)!</p>
<p>(But these $10 would also turn into a thousand dollars. Even in a million or a billion! If the purchase was more expensive. In that case our $10 would make the increasing number of its cycles, circuits from hands to hands. That&#39;s just the procedure!)</p>
<p>So, what happens in today&rsquo;s world!? It appears that banks also &quot;draw&quot; money without problems?! Not only Fed can produce money, but the banks either! And in fact, these banks multiply money without any control! And we&#39;re still wondering, why does the banker live better? Is it clear now, why? The one, who produces the money, of course, lives better!</p>
<p>But this is not enough! From this moment poor Adam will never be able to repay his debts owed to the bank! No matter how hard he would work. Now he is in slavery to the bank, in credit bondage forever. Because those $90, which he owes to Leonard, do not exist in nature! At all! Sly Leonard made this money out of nothing; he created them out of thin air! Just one click! And $10 turned into $200.</p>
<p>Yes, but you can object reasonably that the bank itself owes $100 to Steven. And it turns out, that bank is in credit bondage to Steven and it won&rsquo;t be able to repay its debts owed to Steven either. So where is the bank&rsquo;s profit? What&#39;s the trick?</p>
<p>Ha! You ask what the trick is! This trick is in the fact, that bank has a lot of such &quot;Stevens&quot;, thousands and millions, and they will never come for their money all at once. If one Steven comes, the bank will return him the money of ten other depositors, that&#39;s it. It means that the bank&rsquo;s debt is neither dangerous nor burdensome. In fact, bank&rsquo;s debt is virtual, it exists only on the paper or in the computer program. It will never be repaid in reality. Only in case of panic it happens, when frightened &quot;Stevens&quot; suddenly come for their money &mdash; all at once! Or maybe you know any other reason why banks go bankrupt from time to time? Here&#39;s why. Because there is no enough money for all depositors! There is a 90% of thin air in the bank vaults.</p>
<p>Thus, the bank is OK. It sails before the wind. We don&rsquo;t need to worry about it. But our Adam has serious problems now. He has to repay all the debts owed in bank! Completely!! Moreover with interests and, possibly, penalties. He will be forced to take new credits in order to repay the old ones. Then again the new loan&hellip; and again... and again&hellip; endlessly, until his death! And there is no way out of this credit running knot. It does not exist in principle! That&#39;s it! Trap has been slammed. Now Adam is a perpetual debtor of the bank. He is a slave. From now on he will work for the bank for years on end... Until he dies. But still he won&rsquo;t repay the debts. And after his death his children and grandchildren will work for this bank. They all are the future servants of banks. More precisely, they are servants of this inefficient and unfair global financial system, which spawned this ruthless and inhuman mechanism. And this mechanism must be finally destroyed.</p>
<p>A new fair financial system will be established!</p>
<p>Financial Apocalypse! That&rsquo;s the only thing that can break our financial chains and save us all. Release us finally from the continuous slavery. Everything old will burn in its fire and the new will appear. The Fed will be removed from power and will no longer develop social inequality. The banks as they are now will simply disappear. They will stop robbing the people. In fact the banks do not produce anything useful. What useful can they do? Give credits at plundering interests? As a result all the population is burdened with debts.</p>
<p>Why do the banks get interests for the credit at all? Have you ever thought about it? Usury was always despised by all nations, and now it is legalized. Why? If a person takes a loan in the bank, then not for nothing, but to do something good, to realize some project. But he applies his efforts for the welfare of the society including bankers. Making something useful for all of us. We should encourage such people, making discounts but not collecting from them huge interests!</p>
<p>Nevertheless, modern banks were created for other purposes. They aren&rsquo;t interested in the society but in their own goals. People aren&rsquo;t important for them. Modern banks are loyal servants of the Fed, hypocritical agents, misusing the products of labor of common people. The current financial system is merely destructing us. And it will continue attacking us, and then our children and grandchildren. It will get even worse if nothing changes. We will destroy the existing financial system and build new &mdash; fair and honest! We have no other choice. We are not slaves. We are people. And we choose freedom!</p>
<p><em>And this freedom is almost here already. Now, thanks to MMM financial Apocalypse is inevitable. Unavoidable! Since now it&rsquo;s just the question of time. The seed was dropped. And it would grow. It&rsquo;s already growing. Right now, at this moment! It will not perish!</em></p>
<p>What does MMM stand for?</p>
<p>MMM is a Global Mutual Aid Fund, World people&#39;s Bank, Financial Social Network &mdash; or any definition whatsoever. The point is not in the title. The bottom line is that this is a voluntary informal association of millions and millions of people throughout the Earth, rebelled against the financial slavery, chose to declare war against the Fed and banks. (And to win this war!!) And for this aim they have consolidated their capital &mdash; even though there are small amounts, owing to a great number, that is millions of people, it&#39;s already the power. Awesome and invincible power, growing every day!</p>
<p>Well how do banks exist? Thanks to bankers? Billionaires? No, due to the same ordinary people who deposit their modest savings there. MMM takes the wind out of banks&#39; sails making people see the reality. Why do the people bring their money to the banks at the exorbitant interests? Because they have no other choice. Banks are monopolists: there is no other place to bring money to. All banks are just the same, and controlled by the FED. They simply destroy ordinary people.</p>
<p>And now we have an alternative &mdash; MMM! It&rsquo;s something close to our hearts! Here people help each other. Today you help and tomorrow you will be helped. It&rsquo;s the main principle of MMM. Do you really want bankers to buy another limousine or house for your money? You should not become another slave. Better join MMM and your money will help those who really need it! Poor people, retirees, disabled people&hellip;Woman with many children. Love thy neighbour! Help him.</p>
<p>It&rsquo;s a kind of common storage box where people save their money and then take it when needed. The amount you need at the certain moment. (They do not steel but namely take money)!</p>
<p>Actually, people don&rsquo;t need a lot of money. They need consciousness that they have it. Confidence in tomorrow&rsquo;s day is what everybody really needs. It is just MMM that gives this confidence! It gives a feeling of partnership, that you aren&rsquo;t alone! At the difficult moment you will never be abandoned but you will always be helped and supported! MMM is a unit of new society, brighter and better. New world, where there won&rsquo;t be money. Current money. Where everything will be otherwise&hellip; Fair and honest. Where there won&rsquo;t be any slaves or owners. Where everybody will work for their own pleasure and for the whole society. Where Good will defeat Evil! It will be so! There are no doubts!!</p>
<p>Welcome to the System! Together we will change the world!</p>


<div class="join">join our community</div> 


</div>
<?php
    include('Footer.php');
    
 ?>
</body>
</html>